### PR TITLE
check if :flipped on search

### LINKED ISSUE #75: undefined method `>' for nil:NilClass
```
NoMethodError: undefined method `>' for nil:NilClass
  from action_view/helpers/date_helper.rb:100:in `distance_of_time_in_words'
  from /app/views/index.haml:27:in `block (2 levels) in singleton class'
  from /app/views/index.haml:22:in `each'
  from /app/views/index.haml:22:in `block in singleton class'
  from tilt/template.rb:170:in `call'
  from tilt/template.rb:170:in `evaluate'
  from tilt/haml.rb:19:in `evaluate'
  from tilt/template.rb:109:in `render'
  from sinatra/base.rb:823:in `render'
  from sinatra/base.rb:677:in `haml'
  from /app/sixnines.rb:139:in `block in <top (required)>'
  from sinatra/base.rb:1611:in `call'
  from sinatra/base.rb:1611:in `block in compile!'
  from sinatra/base.rb:975:in `block (3 levels) in route!'
  from sinatra/base.rb:994:in `route_eval'
  from sinatra/base.rb:975:in `block (2 levels) in route!'
  from sinatra/base.rb:1015:in `block in process_route'
  from sinatra/base.rb:1013:in `catch'
  from sinatra/base.rb:1013:in `process_route'
  from sinatra/base.rb:973:in `block in route!'
  from sinatra/base.rb:972:in `each'
  from sinatra/base.rb:972:in `route!'
  from sinatra/base.rb:1085:in `block in dispatch!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:1082:in `dispatch!'
  from sinatra/base.rb:907:in `block in call!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:907:in `call!'
  from sinatra/base.rb:895:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/commonlogger.rb:33:in `call'
  from sinatra/base.rb:219:in `call'
  from sinatra/base.rb:212:in `call'
  from rack/head.rb:13:in `call'
  from rack/methodoverride.rb:22:in `call'
  from sinatra/base.rb:182:in `call'
  from sinatra/base.rb:2013:in `call'
  from sinatra/base.rb:1487:in `block in call'
  from sinatra/base.rb:1787:in `synchronize'
  from sinatra/base.rb:1487:in `call'
  from rack/handler/webrick.rb:88:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

### PR DESCRIPTION
**Pull request by pdacostaporto**
Fixes #75.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#79` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @pdacostaporto, total is [+30](http://www.0crat.com/u/pdacostaporto).

**Comment by yegor256** [comment]
@rultor merge

**Comment by pdacostaporto** [comment]
@yegor256 same as #80 here.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
