### PR TITLE
pulse

### PR DESCRIPTION
**Pull request by pdacostaporto**
Solves #36

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#85` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @pdacostaporto, total is [+135](http://www.0crat.com/u/pdacostaporto).

**Comment by yegor256** [comment]
@pdacostaporto I didn't understand why do we need a DynamoDB table for that? We need just one counter, to count how many pings we did after the restart of the app. We can use just a simple global variable for that. We don't need to count per endpoint, since we already count that. All we need is a "total since reboot". Or I didn't understand your code?

**Comment by pdacostaporto** [comment]
@yegor256 well... i had some thoughts which led to the table idea. I automatically tend to avoid globals in code (is that what you mean?) and singletons to avoid concurrency issues, coupling, mutability and those evil things (although maybe there's a way to avoid them, I'm not sure). DynamoDB handles concurrency automatically, so it was possible to store the count there without those issues.  Maybe concurrency its not an issue but maybe I'm not sure because I'm not sure about how this application works. I also found some examples of visit counters stored in databases, so it didn't look like a bad idea.

It's possible that you didn't understand the code. It works with an only global counter. Yes: there's a whole table for just one record; couldn't find out other way to store it.

Anyway, should I use a global variable in the code then?

**Comment by yegor256** [comment]
@pdacostaporto let's go with a global variable for now, of class, say `TotalPings`. An instance of this class we will create at `sixnines.rb` initialization method and then pass to the endpoints. How to handle the concurrency is a good question. I'm not really an expert in Ruby in this area. Maybe there are some gems for that?

**Comment by pdacostaporto** [comment]
@yegor256 I'm thinking about two options:
-[AtomicFixNum](http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/AtomicFixnum.html) from [Concurrent Ruby](https://github.com/ruby-concurrency/concurrent-ruby) gem: a mutable value. 
-[Thread::Mutex](https://ruby-doc.org/core-2.4.1/Thread/Mutex.html) for synchronizing an immutable global value.

The first option looks easier, but with more magic. What do you think?

**Comment by pdacostaporto** [comment]
I did it with AtomicFixnum in #87. If it's OK, I'll close this.

**Comment by yegor256** [comment]
@pdacostaporto yes, #87 seems correct

**Pull request closed without merging**
