### PR TITLE
multiple exception catching

### PR DESCRIPTION
**Pull request by pdacostaporto**
Solves #81 and #83. `resource.rb` was having a lot of stuff so I refactored it in multiple classes.

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#86` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @pdacostaporto, total is [+150](http://www.0crat.com/u/pdacostaporto).

**Comment by yegor256** [comment]
@pdacostaporto I like your idea of making this code more extendable, but I don't think we need "vertical" decoration here. All of these "exception processors" a very similar in what they are doing. Would be better to just create an array of functions, which will try to recover from an exception and if it's not possible, return an error code or something like this. Making many classes which are doing almost same things is a not a good design. Check this too: http://www.yegor256.com/2015/10/01/vertical-horizontal-decorating.html

**Comment by pdacostaporto** [comment]
@yegor256 you mean something like:

CheckedResponse.new(
  HTTPResponse.new(http, req),
  ResponseChecks(
    ZlibBuferErrorCheck.new,
    ProxyAuthenticationRequiredCheck.new,
    SocketErrorCheck.new,
    TimeoutCheck.new,
    NetworkUnreachableCheck.new
  ).receive

as return value of resource.take?

**Comment by pdacostaporto** [comment]
@yegor256 what about now?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
