### PR TITLE
Editing URL

### PR DESCRIPTION
**Pull request by pdacostaporto**
Solves #93.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#96](https://github.com/yegor256/sixnines/issues/96) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@null[/z](https://www.0crat.com/u/null) everybody who has role `REV` is banned at [#96](https://github.com/yegor256/sixnines/issues/96); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by pdacostaporto** [comment]
@yegor256 checks are failing but because the build is failing for `master`. What should we do?

**Comment by 0crat** [comment]
@null[/z](https://www.0crat.com/u/null) everybody who has role `REV` is banned at [#96](https://github.com/yegor256/sixnines/issues/96); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@null[/z](https://www.0crat.com/u/null) everybody who has role `REV` is banned at [#96](https://github.com/yegor256/sixnines/issues/96); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@null[/z](https://www.0crat.com/u/null) everybody who has role `REV` is banned at [#96](https://github.com/yegor256/sixnines/issues/96); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@null[/z](https://www.0crat.com/u/null) everybody who has role `REV` is banned at [#96](https://github.com/yegor256/sixnines/issues/96); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@null[/z](https://www.0crat.com/u/null) everybody who has role `REV` is banned at [#96](https://github.com/yegor256/sixnines/issues/96); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@null[/z](https://www.0crat.com/u/null) everybody who has role `REV` is banned at [#96](https://github.com/yegor256/sixnines/issues/96); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@null[/z](https://www.0crat.com/u/null) everybody who has role `REV` is banned at [#96](https://github.com/yegor256/sixnines/issues/96); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@null[/z](https://www.0crat.com/u/null) everybody who has role `REV` is banned at [#96](https://github.com/yegor256/sixnines/issues/96); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@null[/z](https://www.0crat.com/u/null) everybody who has role `REV` is banned at [#96](https://github.com/yegor256/sixnines/issues/96); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@null[/z](https://www.0crat.com/u/null) everybody who has role `REV` is banned at [#96](https://github.com/yegor256/sixnines/issues/96); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@null[/z](https://www.0crat.com/u/null) everybody who has role `REV` is banned at [#96](https://github.com/yegor256/sixnines/issues/96); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#96` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#96](https://github.com/yegor256/sixnines/issues/96) is now out of scope

**Pull request merged**
